### 1. register new user
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name": "tester",
  "email": "tester@test.de",
  "password": "strengGeheim123"
}

### 2. login success
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "tobias@test.de",
  "password": "strengGeheim123"
}

### 3. login wrong password (401)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "tobias@test.de",
  "password": "falschesPasswort"
}

### 4. try to login
GET http://localhost:8080/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0b2JpYXNAdGVzdC5kZSIsImlhdCI6MTc4ODA4NDU5OCwiZXhwIjoxNzg4MTcwOTk4fQ.bJuPh5rk2LMhpjjU8Hbnl_XveFS6DGa5S_0BHmQzFDo

### 5. admin page
GET http://localhost:8080/api/admin/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0b2JpYXNAdGVzdC5kZSIsImlhdCI6MTc4ODA4NDU5OCwiZXhwIjoxNzg4MTcwOTk4fQ.bJuPh5rk2LMhpjjU8Hbnl_XveFS6DGa5S_0BHmQzFDo

### 6. get all notes
GET http://localhost:8080/api/notes/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0b2JpYXNAdGVzdC5kZSIsImlhdCI6MTc4ODA4NDU5OCwiZXhwIjoxNzg4MTcwOTk4fQ.bJuPh5rk2LMhpjjU8Hbnl_XveFS6DGa5S_0BHmQzFDo
